# Generated by Django 5.1.2 on 2024-10-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=250)),
                ('image_url', models.URLField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organizers')),
            ],
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(blank=True, choices=[('General', 'General'), ('VIP', 'VIP'), ('Student', 'Student'), ('Complimentary', 'Complimentary')], max_length=250)),
                ('availability_status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Sold Out', 'Sold Out'), ('Limited', 'Limited')], max_length=250)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
        ),
    ]
