# Generated by Django 5.1.2 on 2024-10-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organizers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organizers',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizers',
            name='phone',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organizers',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='discount_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tickets',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='stock_count',
            field=models.IntegerField(null=True),
        ),
    ]
